# Generated by Django 3.1.2 on 2022-03-08 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MinValueValidator(2200)]),
        ),
    ]
