# Generated by Django 3.1.2 on 2022-03-11 07:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220308_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MaxValueValidator(1900), django.core.validators.MinValueValidator(2300)]),
        ),
    ]
