# Generated by Django 3.1.2 on 2022-03-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20220324_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
    ]
