# Generated by Django 3.1.2 on 2022-03-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('movie', '0005_auto_20220324_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='genre.Genre'),
        ),
    ]
